<a href="https://colab.research.google.com/github/Wredina/Teaching_Python/blob/main/homework/final_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib.pyplot as plt

В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без
get_dummies?

In [2]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  robot
2  human
3  robot
4  robot

In [15]:
data.loc[data["whoAmI"] == "human" , "human"] = "I_Am_A_Human"
data.loc[data['whoAmI'] == "robot", "robot"] = "I_Am_A_Toster"
data.loc[(data["whoAmI"] == "robot") & (data["robot"] == 'I_Am_A_Toster'), "human"] = "i_am_not_a_Human"
data.loc[(data["whoAmI"] == "human") & (data["human"] == 'I_Am_A_Human'), "robot"] = "i_am_NOT_a_Toster"

data

   whoAmI             human              robot
0   robot  i_an_not_a_Human      I_Am_A_Toster
1   robot  i_an_not_a_Human      I_Am_A_Toster
2   human      I_Am_A_Human  i_am_NOT_a_Toster
3   robot  i_an_not_a_Human      I_Am_A_Toster
4   robot  i_an_not_a_Human      I_Am_A_Toster
5   human      I_Am_A_Human  i_am_NOT_a_Toster
6   robot  i_an_not_a_Human      I_Am_A_Toster
7   human      I_Am_A_Human  i_am_NOT_a_Toster
8   human      I_Am_A_Human  i_am_NOT_a_Toster
9   human      I_Am_A_Human  i_am_NOT_a_Toster
10  human      I_Am_A_Human  i_am_NOT_a_Toster
11  human      I_Am_A_Human  i_am_NOT_a_Toster
12  human      I_Am_A_Human  i_am_NOT_a_Toster
13  robot  i_an_not_a_Human      I_Am_A_Toster
14  robot  i_an_not_a_Human      I_Am_A_Toster
15  robot  i_an_not_a_Human      I_Am_A_Toster
16  human      I_Am_A_Human  i_am_NOT_a_Toster
17  human      I_Am_A_Human  i_am_NOT_a_Toster
18  robot  i_an_not_a_Human      I_Am_A_Toster
19  robot  i_an_not_a_Human      I_Am_A_Toster